//region Core Types and Interfaces

export type Urgency = 'low' | 'medium' | 'high' | 'critical' | 'informational';

export type InsightType =
    'general' | 'predictive' | 'actionable' | 'correlation' | 'anomaly' |
    'sentiment' | 'geospatial' | 'multimedia' | 'risk' | 'opportunity' |
    'efficiency' | 'compliance' | 'market' | 'customer' | 'security' |
    'ethical' | 'resource' | 'sustainability' | 'trend' | 'forecasting' |
    'optimization' | 'recommendation';

export type ActionPriority = 'low' | 'medium' | 'high';

export type ActionStatus = 'pending' | 'in-progress' | 'completed' | 'deferred';

export type PredictionTrend = 'up' | 'down' | 'stable';

export type VisualizationType = 'chart' | 'map' | 'graph';

export type InsightStatus = 'active' | 'archived' | 'dismissed' | 'resolved';

export interface RelatedEntity {
    type: string;
    id: string;
    name: string;
}

export interface RecommendedAction {
    id: string;
    description: string;
    priority: ActionPriority;
    status: ActionStatus;
}

export interface Prediction {
    target: string;
    value: number;
    confidence: number;
    trend: PredictionTrend;
}

export interface Visualization {
    type: VisualizationType;
    data: any;
    options?: any;
}

export interface EthicalConsideration {
    aspect: string;
    score: number;
    details: string;
}

export interface Feedback {
    rating: number;
    comment: string;
    timestamp: string; // ISO string
}

/**
 * Represents an extended AI Insight with detailed properties for display and interaction.
 * This interface is a comprehensive structure for insights generated by an AI system.
 */
export interface ExtendedAIInsight {
    id: string;
    title: string;
    description: string;
    urgency: Urgency;
    type: InsightType;
    timestamp: string; // ISO string (e.g., "2023-10-27T10:00:00Z")
    source: string; // e.g., 'Sales Data', 'Marketing Analytics', 'IoT Sensors'
    dataPoints?: any[]; // Raw data points supporting the insight (can be complex objects)
    metrics?: { [key: string]: any }; // Key metrics related to the insight (e.g., { 'revenueImpact': 12000, 'customerChurnRate': 0.05 })
    relatedEntities?: RelatedEntity[]; // Entities related to the insight (e.g., specific customers, products, regions)
    recommendedActions?: RecommendedAction[]; // Concrete actions suggested by the AI
    predictions?: Prediction[]; // Future predictions associated with the insight
    visualizations?: Visualization[]; // Data for embedding charts, maps, or graphs
    explanation?: string; // Explainable AI (XAI) narrative explaining 'why' the insight was generated
    feedback?: Feedback[]; // User feedback on the insight's accuracy or usefulness
    modelVersion?: string; // Identifier for the AI model version that generated the insight
    ethicalConsiderations?: EthicalConsideration[]; // Assessment of ethical implications
    tags?: string[]; // Categorization tags for filtering and organization
    status?: InsightStatus; // Current status of the insight (e.g., active, resolved, dismissed)
    impactScore?: number; // Calculated numerical score representing the potential impact
}

//endregion