# === Backend CI Pipeline ===
# Builds and tests a Go-based microservice. This workflow demonstrates:
# - Using service containers (Postgres) for integration testing.
# - Building a Docker container.
# - Pushing the container to GitHub Container Registry (GHCR).

name: 'Backend CI: Test, Build, Push Image'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'services/payments-api/**'
      - 'github/workflows/02-backend-ci.yml'

jobs:
  build-payments-api:
    name: 'Payments API CI'
    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Service containers provide a clean database for each run
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: 'Run Unit Tests'
        working-directory: ./services/payments-api
        run: go test ./...

      - name: 'Run Integration Tests'
        working-directory: ./services/payments-api
        env:
          # Provide the test database connection string to the integration tests
          TEST_DATABASE_URL: "postgres://testuser:testpassword@localhost:5432/testdb?sslmode=disable"
        run: go test -tags=integration ./...

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and Push Docker Image'
        uses: docker/build-push-action@v5
        with:
          context: ./services/payments-api
          push: true
          tags: ghcr.io/${{ github.repository }}/payments-api:${{ github.sha }}
