# === Documentation CI/CD ===
# This workflow automatically builds and deploys the documentation website
# to GitHub Pages whenever changes are pushed to the 'docs' directory.

name: 'Docs CI: Build and Deploy'

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'github/workflows/07-documentation-ci.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup Pages'
        uses: actions/configure-pages@v4

      - name: 'Build with Jekyll'
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      - name: 'Upload Artifact'
        uses: actions/upload-pages-artifact@v3

      - name: 'Deploy to GitHub Pages'
        id: deployment
        uses: actions/deploy-pages@v4
