# === AI PR Summarizer ===
# This workflow uses the Gemini API to summarize pull requests.
# It reads the code changes (the diff) and generates a plain-English
# summary of what the PR does, then posts it as a comment.

name: 'AI: Summarize PR'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      pull-requests: 'write'
    
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for a better diff

      - name: 'Get PR Diff'
        id: get_diff
        run: |
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          # Truncate diff if it's too large for the API
          if [ ${#DIFF} -gt 100000 ]; then
            DIFF=$(echo "$DIFF" | head -c 100000)
          fi
          # Escape for JSON
          DIFF=$(echo "$DIFF" | jq -s -R .)
          echo "DIFF=$DIFF" >> $GITHUB_OUTPUT

      - name: 'Generate Summary with Gemini'
        id: gemini_summary
        run: |
          API_URL="https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${{ secrets.GEMINI_API_KEY }}"
          
          PROMPT="You are a senior software engineer. Analyze the following git diff and provide a concise, high-level summary for a pull request comment. Focus on the 'why' and 'what' of the changes in bullet points. Diff: ${{#steps.get_diff.outputs.DIFF}}"

          # Using curl to call the Gemini API
          RESPONSE=$(curl -s -H 'Content-Type: application/json' -d \
            "{ 'contents': [{ 'parts': [{ 'text': $PROMPT }] }] }" \
            "$API_URL")

          SUMMARY=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')
          SUMMARY=$(echo "$SUMMARY" | jq -s -R .)
          echo "SUMMARY=$SUMMARY" >> $GITHUB_OUTPUT

      - name: 'Comment on PR'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const summary = ${{ steps.gemini_summary.outputs.SUMMARY }};
            const body = `### 🤖 AI Summary\n\n${summary}`;
            
            // Check for existing AI comments and update if necessary
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const aiComment = comments.find(comment => comment.user.login === 'github-actions[bot]' && comment.body.includes('AI Summary'));
            
            if (aiComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: aiComment.id,
                body: body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body,
              });
            }
