openapi: 3.0.3
info:
  title: "Demo Bank API: Hyper-Personalized Economic Governance - Quantum Nexus Edition"
  description: |
    Step into the **Quantum Nexus**, the revolutionary layer of the Demo Bank API where individual and corporate entities transcend traditional financial interactions to actively shape and influence the global economic landscape. This cutting-edge interface empowers users to propose, simulate, and participate in the governance of micro- and macro-economic policies, leveraging the unparalleled predictive capabilities of our Artificial General Intelligence, **Quantum**.

    This API provides direct programmatic access to a suite of advanced tools, allowing you to:
    - **Formulate Micro-Economic Policy Proposals:** Submit granular policy ideas, from personal carbon offset schemes to localized investment directives or industry-specific regulatory suggestions.
    - **Run Quantum-Powered Macro-Economic Simulations:** Instantly analyze the multi-faceted impacts of proposed policies on global markets, GDP, employment, inflation, and environmental metrics, with real-time feedback from our AI.
    - **Engage in Decentralized Economic Governance:** Participate in a consensus mechanism to vote on, refine, and potentially enact policies, integrating user-driven insights into the future of finance.
    - **Anticipate Future Market Dynamics:** Gain access to AI-driven foresight into how various economic interventions could shift market equilibria, asset valuations, and resource distribution.

    The Quantum Nexus redefines financial agency, transforming users from passive participants to active architects of a more intelligent, equitable, and sustainable economic future. This is not just about managing wealth; it's about governing prosperity, powered by the collective intelligence of humanity and the predictive prowess of AI.
servers:
  - url: "/"
tags:
  - name: "Users & Identity Management"
    description: "Comprehensive management of user profiles, advanced biometric authentication, multi-factor security, and digital identity verification (KYC/AML)."
  - name: "Economic Policy Proposals (Individual)"
    description: "Endpoints for individual users to propose, refine, and track micro-economic policy initiatives within the Demo Bank ecosystem and beyond."
  - name: "Economic Policy Proposals (Corporate)"
    description: "Endpoints for corporate entities to submit, analyze, and advocate for macro-economic regulatory changes, market interventions, or industry-specific policies."
  - name: "AI Macro-Economic Simulation Engine"
    description: "Run complex, multi-variable simulations of economic policies, market shocks, and global trends with Quantum AI's predictive models, assessing impacts on GDP, inflation, employment, and various sectors."
  - name: "Decentralized Economic Governance & Voting"
    description: "Engage in the collective governance process: review proposed policies, cast votes, and participate in the consensus mechanisms that shape future economic directives."
  - name: "Future Market Prediction & Foresight"
    description: "Access AI-driven predictive models offering foresight into asset class performance, commodity price trends, and geopolitical economic shifts under various policy scenarios."
  - name: "Social & Environmental Impact Modeling"
    description: "Quantify the projected social (employment, inequality, welfare) and environmental (carbon emissions, resource depletion) impacts of economic policies via advanced AI models."
  - name: "Global Financial Policy Orchestration"
    description: "Endpoints for modeling cross-border economic policy interactions, trade agreements, currency impacts, and international capital flow regulations."
  - name: "Resource Allocation & Optimization"
    description: "Leverage AI to optimize the allocation of financial capital, human resources, and natural assets under simulated economic policies or market conditions."
  - name: "Regulatory Impact Assessment"
    description: "Predict the effects of new or changed regulations on specific industries, compliance burdens, innovation rates, and competitive landscapes, guided by Quantum AI."
  - name: "AI Advisor (Quantum)"
    description: "Engage with our state-of-the-art conversational AI, Quantum, for deeply personalized financial insights, proactive advice, and autonomous task execution via a rich tool ecosystem."
  - name: "Quantum Weaver (Business Incubation)"
    description: "The AI-driven seed funding and incubation platform. Submit, refine, and track business plans, receive AI-generated feedback, and secure investment capital."
  - name: "Corporate Finance - Compliance & Risk"
    description: "Advanced access to compliance cases, AI-powered financial anomaly detection, real-time risk assessments, and automated sanction screening for enterprise clients."
  - name: "Real-time Analytics & Predictive Intelligence"
    description: "Unlocking advanced, AI-driven analytics dashboards, predictive financial forecasting, and custom report generation for both personal and corporate users."
  - name: "Global Payments & Foreign Exchange"
    description: "Facilitate secure, multi-currency transactions and international transfers with real-time and predictive foreign exchange rate analysis."
  - name: "Sustainability & ESG Impact"
    description: "Measure, track, and improve personal and corporate environmental, social, and governance (ESG) impact, including carbon footprint analysis and green investment opportunities."
  - name: "Investments & Portfolio Intelligence"
    description: "Sophisticated management of investment portfolios, AI-driven asset discovery, ESG impact analysis, predictive growth simulations, and automated rebalancing strategies."
  - name: "Enterprise Risk & Fraud Prevention"
    description: "Define custom AI-powered fraud detection rules, monitor enterprise-wide risk alerts, leverage transactional risk scoring, and manage security incidents proactively."

paths:
  # Base user endpoint from seed (for context)
  /users/me:
    get:
      tags:
        - "Users & Identity Management"
      summary: "Retrieve Comprehensive Current User Profile"
      description: "Fetches the complete and dynamically updated profile information for the currently authenticated user, encompassing personal details, security status, gamification level, loyalty points, and linked identity attributes."
      operationId: "getCurrentUserEnhancedProfile"
      security:
        - oAuth2Auth: [read:profile, read:security, read:rewards, read:identity]
      responses:
        "200":
          description: "The user's complete, enriched profile information."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: "Unauthorized. Authentication token is missing, invalid, or expired."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          $ref: "#/components/responses/ForbiddenError"

  # --------------------------------------------------------------------------------------------------------------------
  # Economic Policy Proposals (Individual) - PATHS
  # --------------------------------------------------------------------------------------------------------------------
  /economic-governance/individual/proposals:
    get:
      tags:
        - "Economic Policy Proposals (Individual)"
        - "Decentralized Economic Governance & Voting"
      summary: "List All Personal Micro-Economic Policy Proposals"
      description: "Retrieves a comprehensive, paginated list of all micro-economic policy proposals submitted by the authenticated individual user, including their current status, AI sentiment analysis, and community engagement metrics."
      operationId: "listIndividualPolicyProposals"
      security:
        - oAuth2Auth: [read:economic_proposals]
      parameters:
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/Offset"
        - name: status
          in: query
          description: "Filter proposals by their current processing status."
          schema:
            type: string
            enum: [Draft, Submitted, Under_AI_Review, Awaiting_Vote, Approved, Rejected, Implemented, Archived]
            default: Submitted
        - name: impactType
          in: query
          description: "Filter proposals by their primary intended impact type."
          schema:
            type: string
            enum: [Financial, Environmental, Social, Technological, Regulatory]
      responses:
        "200":
          description: "A paginated list of individual micro-economic policy proposals."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedIndividualPolicyProposals"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
    post:
      tags:
        - "Economic Policy Proposals (Individual)"
        - "Decentralized Economic Governance & Voting"
        - "AI Macro-Economic Simulation Engine"
      summary: "Submit a New Personal Micro-Economic Policy Proposal"
      description: "Allows an individual user to submit a new, detailed micro-economic policy proposal for AI analysis, community discussion, and potential inclusion in decentralized governance voting. The AI immediately begins an initial feasibility and impact assessment."
      operationId: "submitIndividualPolicyProposal"
      security:
        - oAuth2Auth: [write:economic_proposals, interact:macro_simulation]
      requestBody:
        required: true
        description: "The complete payload for a new individual micro-economic policy proposal."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IndividualPolicyProposalCreationRequest"
      responses:
        "202":
          description: "Policy proposal submitted successfully for AI review. Returns the proposal ID."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IndividualPolicyProposalStatus"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "409":
          description: "A similar policy proposal already exists or is under review."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /economic-governance/individual/proposals/{proposalId}:
    get:
      tags:
        - "Economic Policy Proposals (Individual)"
        - "AI Macro-Economic Simulation Engine"
      summary: "Get Detailed Individual Policy Proposal with AI Analysis"
      description: "Retrieves granular details of a specific individual micro-economic policy proposal, including its full textual content, AI-generated feasibility report, predicted impacts across various economic and social metrics, and current sentiment analysis."
      operationId: "getIndividualPolicyProposalDetails"
      security:
        - oAuth2Auth: [read:economic_proposals]
      parameters:
        - $ref: "#/components/parameters/ProposalId"
      responses:
        "200":
          description: "Detailed individual policy proposal with AI analysis."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IndividualPolicyProposalDetail"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    put:
      tags:
        - "Economic Policy Proposals (Individual)"
      summary: "Update an Existing Personal Micro-Economic Policy Proposal"
      description: "Allows the owner to modify their existing micro-economic policy proposal. This action may trigger a re-evaluation by the AI engine if significant changes are detected."
      operationId: "updateIndividualPolicyProposal"
      security:
        - oAuth2Auth: [write:economic_proposals]
      parameters:
        - $ref: "#/components/parameters/ProposalId"
      requestBody:
        required: true
        description: "Updated content for the individual micro-economic policy proposal."
        content:
          application